### ISSUE TITLE
Check templates all live under a templates/ folder

### ISSUE THREAD

**Issue by ashb** [lukaszraczylo/salt-lint#6]
For instance

``` yaml
/etc/iptables-rules:
  file.managed:
    - source: salt://firewall/iptables-rules
    - template: jinja
    - user: root
    - group: root
```

If there is a `template: jinja` attribute the source attribute should have `/templates/` in it somewhere.
